spring.application.name=pokemon

# Server configuration
server.port=3000
server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=jdbc:postgresql://pokemonbattlearena.ctam4gw68b95.us-east-1.rds.amazonaws.com:5432/pokemondb
spring.datasource.username=admin_pokemon
spring.datasource.password=TecmilenioPokemonArena
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=pokemonBattleArenaSecretKeyForJWTAuthenticationTokenMustBeVeryLongForSecurityReasonsAndToComplyWithTheHS512Algorithm
jwt.expiration=86400000

# Logging Configuration
logging.level.org.springframework.security=INFO
logging.level.com.backend.pokemon=INFO

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pokemon.battle.notification@gmail.com
spring.mail.password=wihs owit pkmu dovh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com