on:
  pull_request:
    types: [opened]
jobs:
  request-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Request two code reviews
      uses: peter-evans/create-or-request-review@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        required-reviewers: cesarmendozav
        num-additional-reviewers: 1
        require-all-reviews: true
